Optimize the motd script a bit.

diff --git a/release/src/router/others/mymotd b/release/src/router/others/mymotd
--- a/release/src/router/others/mymotd
+++ b/release/src/router/others/mymotd
@@ -4,16 +4,23 @@
 #
 # Version 0.5 written by Monter, modified by Shibby
 #
-MOTD_ON=`/bin/nvram get sshd_motd`
+
+PATH=$PATH:/usr/bin
+
+nvram export --dump0 | awk -F = 'BEGIN {RS="\\\000";OFS="=\"";ORS="\"\n"}; /^([lw]an[0-9]?_(ipaddr|netmask)|landevs|router_name|[a-z0-9]+_hwaddr|t_cafree|t_model_name|sshd_motd|dhcpd[0-9]?_(start|end)ip)|wl[0-9]_(ssid|channel|country)/ { tmp=$1; sub(/^[^=]+=+/,""); print tmp,$0 }' > /tmp/.mymotd.$$ && . /tmp/.mymotd.$$
+rm -f /tmp/.mymotd.$$
 
 #only if enable
-if /usr/bin/[ "$MOTD_ON" == "1" ]; then
+if [ "$sshd_motd" != "1" ]; then
+  exit
+fi
 
 PROFILE=$1
-if /usr/bin/[ "$PROFILE" == "init" ]; then
-sed -i "/mymotd/d" /root/.profile
-/bin/echo "/usr/sbin/mymotd" >> /root/.profile
-else
+if [ "$PROFILE" == "init" ]; then
+  sed -i "/mymotd/d" /root/.profile
+  echo "/usr/sbin/mymotd" >> /root/.profile
+  exit
+fi
 
 # Function calculates number of bit in a netmask
 #
@@ -31,33 +38,22 @@ mask2cidr() {
             192) let nbits+=2;;
             128) let nbits+=1;;
             0);;
-            *) /bin/echo "Error: $dec is not recognised"; exit 1
+            *) echo "Error: $dec is not recognised"; exit 1
         esac
     done
-    /bin/echo "$nbits"
+    echo "$nbits"
 }
 
-LAN1=`/bin/nvram get lan1_ipaddr | /usr/bin/wc -w`
-LAN2=`/bin/nvram get lan2_ipaddr | /usr/bin/wc -w`
-LAN3=`/bin/nvram get lan3_ipaddr | /usr/bin/wc -w`
-LAN4=`/bin/nvram get lan4_ipaddr | /usr/bin/wc -w`
-LAN5=`/bin/nvram get lan5_ipaddr | /usr/bin/wc -w`
-LAN6=`/bin/nvram get lan6_ipaddr | /usr/bin/wc -w`
-LAN7=`/bin/nvram get lan7_ipaddr | /usr/bin/wc -w`
-DUAL=`/bin/nvram get landevs | /bin/grep wl1 | /usr/bin/wc -l`
+DUAL=`echo $landevs | /bin/grep wl1 | wc -l`
 
-WAN_MASK=`/bin/nvram get wan_netmask`
-WAN_NUMBITS=$(mask2cidr $WAN_MASK)
+WAN_NUMBITS=`mask2cidr $wan_netmask`
+LAN_NUMBITS=`mask2cidr $lan_netmask`
 
-LAN_MASK=`/bin/nvram get lan_netmask`
-LAN_NUMBITS=$(mask2cidr $LAN_MASK)
-
-/bin/echo -e "\033[1;34m ======================================================== \033[0m"
-/bin/echo -e "\033[1;32m Welcome to the `/bin/nvram get t_model_name` [`/bin/nvram get router_name`]\033[0m"
-/bin/echo -e "\033[1;31m Uptime: `/usr/bin/uptime | /bin/sed -e 's/,  load/\n Load/'`\033[0m"
-MEMBUFF=`/bin/nvram get t_cafree`
-if /usr/bin/[ "$MEMBUFF" == 1 ]; then
-  /usr/bin/awk '/MemTotal:/{total=$2} \
+echo -e "\033[1;34m ======================================================== \033[0m"
+echo -e "\033[1;32m Welcome to the $t_model_name [ $router_name ]\033[0m"
+echo -e "\033[1;31m Uptime: `uptime | /bin/sed -e 's/,  load/\n Load/'`\033[0m"
+if [ "$t_cafree" == 1 ]; then
+  awk '/MemTotal:/{total=$2} \
        /MemFree:/{free=$2} \
        /Buffers:/{buffers=$2} \
        /^Cached:/{cached=$2} \
@@ -65,8 +61,8 @@ if /usr/bin/[ "$MEMBUFF" == 1 ]; then
         printf " Mem usage: %0.1f", ((total-free-buffers-cached)*100/total); printf "%c", 37; \
         printf " (used %0.2f", (total-free-buffers-cached)/1024; printf " of %0.2f", total/1024; printf " MB)\n"; \
       }' /proc/meminfo
-  if /usr/bin/[ `cat /proc/meminfo | /bin/grep SwapTotal | /usr/bin/awk '{ print $2 }'` -gt 0 ]; then
-  /usr/bin/awk '/SwapTotal:/{stotal=$2} \
+  if [ `cat /proc/meminfo | /bin/grep SwapTotal | awk '{ print $2 }'` -gt 0 ]; then
+  awk '/SwapTotal:/{stotal=$2} \
        /SwapFree:/{sfree=$2} \
        /SwapCached:/{scached=$2} \
        END{ \
@@ -75,14 +71,14 @@ if /usr/bin/[ "$MEMBUFF" == 1 ]; then
        }' /proc/meminfo
   fi
 else
-  /usr/bin/awk '/MemTotal:/{total=$2} \
+  awk '/MemTotal:/{total=$2} \
        /MemFree:/{free=$2} \
        END{ \
         printf " Mem : used %0.1f", ((total-free)*100/total); printf "%c", 37; \
         printf " (%0.2f", (total-free)/1024; printf " of %0.2f", total/1024; printf " MB)\n"; \
       }' /proc/meminfo
-  if /usr/bin/[ `cat /proc/meminfo | /bin/grep SwapTotal | /usr/bin/awk '{ print $2 }'` -gt 0 ]; then
-  /usr/bin/awk '/SwapTotal:/{stotal=$2} \
+  if [ `cat /proc/meminfo | /bin/grep SwapTotal | awk '{ print $2 }'` -gt 0 ]; then
+  awk '/SwapTotal:/{stotal=$2} \
        /SwapFree:/{sfree=$2} \
        END{ \
         printf " Swap usage: %0.1f", ((stotal-sfree)*100/stotal); printf "%c", 37; \
@@ -90,72 +86,63 @@ else
        }' /proc/meminfo
   fi
 fi
-/bin/echo " WAN : `/bin/nvram get wan_ipaddr`/$WAN_NUMBITS @ `/bin/nvram get wan_hwaddr`"
-/bin/echo " LAN : `/bin/nvram get lan_ipaddr`/$LAN_NUMBITS @ DHCP: `/bin/nvram get dhcpd_startip` - `/bin/nvram get dhcpd_endip`"
-if /usr/bin/[ "$LAN1" == "1" ]; then 
-    LAN1_MASK=`/bin/nvram get lan1_netmask`
-    LAN1_NUMBITS=$(mask2cidr $LAN1_MASK)
-    /bin/echo " LAN1: `/bin/nvram get lan1_ipaddr`/$LAN1_NUMBITS @ DHCP: `/bin/nvram get dhcpd1_startip` - `/bin/nvram get dhcpd1_endip`";
+echo " WAN : $wan_ipaddr/$WAN_NUMBITS @ $wan_hwaddr"
+echo " LAN : $lan_ipaddr/$LAN_NUMBITS @ DHCP: $dhcpd_startip - $dhcpd_endip"
+if [ "$lan1_ipaddr" != "" ]; then 
+    LAN1_NUMBITS=`mask2cidr $lan1_netmask`
+    echo " LAN1: $lan1_ipaddr/$LAN1_NUMBITS @ DHCP: $dhcpd1_startip - $dhcpd1_endip";
 fi
-if /usr/bin/[ "$LAN2" == "1" ]; then 
-    LAN2_MASK=`/bin/nvram get lan2_netmask`
-    LAN2_NUMBITS=$(mask2cidr $LAN2_MASK)
-    /bin/echo " LAN2: `/bin/nvram get lan2_ipaddr`/$LAN2_NUMBITS @ DHCP: `/bin/nvram get dhcpd2_startip` - `/bin/nvram get dhcpd2_endip`";
+if [ "$lan2_ipaddr" != "" ]; then 
+    LAN2_NUMBITS=`mask2cidr $lan2_netmask`
+    echo " LAN2: $lan2_ipaddr/$LAN2_NUMBITS @ DHCP: $dhcpd2_startip - $dhcpd2_endip";
 fi
-if /usr/bin/[ "$LAN3" == "1" ]; then 
-    LAN3_MASK=`/bin/nvram get lan3_netmask`
-    LAN3_NUMBITS=$(mask2cidr $LAN3_MASK)
-    /bin/echo " LAN3: `/bin/nvram get lan3_ipaddr`/$LAN3_NUMBITS @ DHCP: `/bin/nvram get dhcpd3_startip` - `/bin/nvram get dhcpd3_endip`";
+if [ "$lan3_ipaddr" != "" ]; then 
+    LAN3_NUMBITS=`mask2cidr $lan3_netmask`
+    echo " LAN3: $lan3_ipaddr/$LAN3_NUMBITS @ DHCP: $dhcpd3_startip - $dhcpd3_endip";
 fi
-if /usr/bin/[ "$LAN4" == "1" ]; then 
-    LAN4_MASK=`/bin/nvram get lan4_netmask`
-    LAN4_NUMBITS=$(mask2cidr $LAN4_MASK)
-    /bin/echo " LAN4: `/bin/nvram get lan4_ipaddr`/$LAN4_NUMBITS @ DHCP: `/bin/nvram get dhcpd4_startip` - `/bin/nvram get dhcpd4_endip`";
+if [ "$lan4_ipaddr" != "" ]; then 
+    LAN4_NUMBITS=`mask2cidr $lan4_netmask`
+    echo " LAN4: $lan4_ipaddr/$LAN4_NUMBITS @ DHCP: $dhcpd4_startip - $dhcpd4_endip";
 fi
-if /usr/bin/[ "$LAN5" == "1" ]; then 
-    LAN5_MASK=`/bin/nvram get lan5_netmask`
-    LAN5_NUMBITS=$(mask2cidr $LAN5_MASK)
-    /bin/echo " LAN5: `/bin/nvram get lan5_ipaddr`/$LAN5_NUMBITS @ DHCP: `/bin/nvram get dhcpd5_startip` - `/bin/nvram get dhcpd5_endip`";
+if [ "$lan5_ipaddr" != "" ]; then 
+    LAN5_NUMBITS=`mask2cidr $lan5_netmask`
+    echo " LAN5: $lan5_ipaddr/$LAN5_NUMBITS @ DHCP: $dhcpd5_startip - $dhcpd5_endip";
 fi
-if /usr/bin/[ "$LAN6" == "1" ]; then 
-    LAN6_MASK=`/bin/nvram get lan6_netmask`
-    LAN6_NUMBITS=$(mask2cidr $LAN6_MASK)
-    /bin/echo " LAN6: `/bin/nvram get lan6_ipaddr`/$LAN6_NUMBITS @ DHCP: `/bin/nvram get dhcpd6_startip` - `/bin/nvram get dhcpd6_endip`";
+if [ "$lan6_ipaddr" != "" ]; then 
+    LAN6_NUMBITS=`mask2cidr $lan6_netmask`
+    echo " LAN6: $lan6_ipaddr/$LAN6_NUMBITS @ DHCP: $dhcpd6_startip - $dhcpd6_endip";
 fi
-if /usr/bin/[ "$LAN7" == "1" ]; then 
-    LAN7_MASK=`/bin/nvram get lan7_netmask`
-    LAN7_NUMBITS=$(mask2cidr $LAN7_MASK)
-    /bin/echo " LAN7: `/bin/nvram get lan7_ipaddr`/$LAN7_NUMBITS @ DHCP: `/bin/nvram get dhcpd7_startip` - `/bin/nvram get dhcpd7_endip`";
+if [ "$lan7_ipaddr" != "" ]; then 
+    LAN7_NUMBITS=`mask2cidr $lan7_netmask`
+    echo " LAN7: $lan7_ipaddr/$LAN7_NUMBITS @ DHCP: $dhcpd7_startip - $dhcpd7_endip";
 fi
-GETCH24=`/bin/nvram get wl0_channel`
-if /usr/bin/[ "$GETCH24" == 0 ]; then CH24="auto"; else CH24=$GETCH24; fi
-/bin/echo " WL0 : `/bin/nvram get wl0_ssid` @ channel: `/bin/nvram get wl0_country`$CH24 @ `/bin/nvram get wl0_hwaddr`"
-if /usr/bin/[ "$DUAL" == "1" ]; then
-  GETCH50=`/bin/nvram get wl1_channel`
-  if /usr/bin/[ "$GETCH50" == 0 ]; then CH50="auto"; else CH50=$GETCH50; fi
-  /bin/echo " WL1 : `/bin/nvram get wl1_ssid` @ channel: `/bin/nvram get wl1_country`$CH50 @ `/bin/nvram get wl1_hwaddr`"
+GETCH24=$wl0_channel
+if [ "$GETCH24" == 0 ]; then CH24="auto"; else CH24=$GETCH24; fi
+echo " WL0 : $wl0_ssid @ channel: $wl0_country$CH24 @ $wl0_hwaddr"
+if [ "$DUAL" == "1" ]; then
+  GETCH50=$wl1_channel
+  if [ "$GETCH50" == 0 ]; then CH50="auto"; else CH50=$GETCH50; fi
+  echo " WL1 : $wl1_ssid @ channel: $wl1_country$CH50 @ $wl1_hwaddr"
 fi
-STHMD_ISENABLED=`/usr/sbin/cru l | /bin/grep "perm_on" | /usr/bin/wc -l`
-STHMD_SUNENABLED=`/usr/sbin/cru l | /bin/grep "sun_on" | /usr/bin/wc -l`
-STHMD_SUNSET=`/usr/sbin/cru l | /bin/grep "stealthsunset" | /usr/bin/awk '{ print $2" "$1 }'`
-STHMD_SUNRISE=`/usr/sbin/cru l | /bin/grep "stealthsunrise" | /usr/bin/awk '{ print $2" "$1 }'`
-STHMD_SCHON=`/usr/sbin/cru l | /bin/grep "stealthsheduleon" | /usr/bin/awk '{ print $2" "$1 }'`
-STHMD_SCHOFF=`/usr/sbin/cru l | /bin/grep "stealthsheduleoff" | /usr/bin/awk '{ print $2" "$1 }'`
-STHMD_SCHONC=`/bin/echo $STHMD_SCHON | /usr/bin/wc -c`
-STHMD_SCHOFFC=`/bin/echo $STHMD_SCHOFF | /usr/bin/wc -c`
-if /usr/bin/[ $STHMD_ISENABLED -gt 0 -o $STHMD_SUNENABLED -gt 0 -o $STHMD_SCHONC -gt 1 -o $STHMD_SCHOFFC -gt 1 ]; then
-/bin/echo " -------------------------------------------------------- "
-  if /usr/bin/[ $STHMD_ISENABLED -gt 0 ]; then
-  /bin/echo " Detected the presence of stealthMode which is now active"
+
+STHMD_ISENABLED=`/usr/sbin/cru l | /bin/grep "perm_on"`
+STHMD_SUNENABLED=`/usr/sbin/cru l | /bin/grep "sun_on"`
+STHMD_SCHON=`/usr/sbin/cru l | awk '/stealthscheduleon/ { print $2" "$1 }'`
+STHMD_SCHOFF=`/usr/sbin/cru l | awk '/stealthsheduleoff/ { print $2" "$1 }'`
+
+if [ "$STHMD_ISENABLED" != "" -o "$STHMD_SUNENABLED" != "" ]; then
+  STHMD_SUNSET=`/usr/sbin/cru l | /bin/grep "stealthsunset" | awk '{ print $2" "$1 }'`
+  STHMD_SUNRISE=`/usr/sbin/cru l | /bin/grep "stealthsunrise" | awk '{ print $2" "$1 }'`
+  echo " -------------------------------------------------------- "
+  if [ $STHMD_ISENABLED -gt 0 ]; then
+    echo " Detected the presence of stealthMode which is now active"
   fi
-  if /usr/bin/[ $STHMD_SUNENABLED -gt 0 ]; then
-  /bin/echo -e "  stealthMode Sunset mode is currently active and is set\n         for sunset at $( /bin/echo $STHMD_SUNSET | /usr/bin/awk '{$1=sprintf("%02d", $1);$2=sprintf("%02d", $2); print $1":"$2 }' ) and sunrise at $( /bin/echo $STHMD_SUNRISE | /usr/bin/awk '{$1=sprintf("%02d", $1);$2=sprintf("%02d", $2); print $1":"$2 }' )"
-  fi
-  if /usr/bin/[ $STHMD_SCHONC -gt 1 -a $STHMD_SCHOFFC -gt 1 ]; then
-  /bin/echo -e "  stealthMode Scheduled mode is currently active and is\n       set for sunset at $( /bin/echo $STHMD_SCHON | /usr/bin/awk '{$1=sprintf("%02d", $1);$2=sprintf("%02d", $2); print $1":"$2 }' ) and sunrise at $( /bin/echo $STHMD_SCHOFF | /usr/bin/awk '{$1=sprintf("%02d", $1);$2=sprintf("%02d", $2); print $1":"$2 }' )"
+  if [ $STHMD_SUNENABLED -gt 0 ]; then
+    echo -e "  stealthMode Sunset mode is currently active and is set\n         for sunset at $( echo $STHMD_SUNSET | awk '{$1=sprintf("%02d", $1);$2=sprintf("%02d", $2); print $1":"$2 }' ) and sunrise at $( echo $STHMD_SUNRISE | awk '{$1=sprintf("%02d", $1);$2=sprintf("%02d", $2); print $1":"$2 }' )"
   fi
 fi
-/bin/echo -e "\033[1;34m ======================================================== \033[0m"
-/bin/echo ""
+if [ "$STHMD_SCHON" != "" -o "$STHMD_SCHOFF" != "" ]; then
+    echo -e "  stealthMode Scheduled mode is currently active and is\n       set for sunset at $( echo $STHMD_SCHON | awk '{$1=sprintf("%02d", $1);$2=sprintf("%02d", $2); print $1":"$2 }' ) and sunrise at $( echo $STHMD_SCHOFF | awk '{$1=sprintf("%02d", $1);$2=sprintf("%02d", $2); print $1":"$2 }' )"
 fi
-fi
+echo -e "\033[1;34m ======================================================== \033[0m"
+echo ""
